/**
 * Per-model endpoint routing for the Command Code Provider API.
 *
 * GENERATED by `node scripts/sync-endpoints.mjs`. Do not hand-edit.
 *
 * The API serves three different route sets, not the two the prose suggests:
 *
 *   ['/chat/completions', '/responses']  67 models — the normal case
 *   ['/messages']                       10 models — Claude
 *   ['/chat/completions']                9 models — NOT served by /responses
 *
 * That third group is the reason this file exists. Routing on "Claude ⇒
 * messages, else responses" sends the 9 chat-completions-only models to
 * `/responses`, and the server answers:
 *
 *   Model "stealth/space-bunny-alpha" is not available on this endpoint.
 *   Call it on /provider/v1/chat/completions instead.
 *
 * `GET /provider/v1/models` is public — no auth — and returns
 * `supported_endpoints` per model, so this table is transcribed from the server
 * rather than guessed. Re-run the script to refresh it.
 */

/** The three routes the API exposes, in the form the model list reports them. */
export type ApiRoute = '/chat/completions' | '/responses' | '/messages';

/** One model's declared routes. An empty list means the server said nothing. */
interface EndpointEntry {
  readonly id: string;
  readonly endpoints: readonly ApiRoute[];
}

const ENDPOINTS: readonly EndpointEntry[] = [
  { id: 'deepseek/deepseek-v4-pro', endpoints: ['/chat/completions', '/responses'] },
  { id: 'deepseek/deepseek-v4-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'deepseek/deepseek-v4-flash-vision-exp', endpoints: ['/chat/completions', '/responses'] },
  { id: 'deepseek/deepseek-v4-flash-fast', endpoints: ['/chat/completions'] },
  { id: 'deepseek/deepseek-v4.1-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'moonshotai/Kimi-K3', endpoints: ['/chat/completions', '/responses'] },
  { id: 'moonshotai/Kimi-K2.7-Code', endpoints: ['/chat/completions', '/responses'] },
  { id: 'moonshotai/Kimi-K2.7-Code-Highspeed', endpoints: ['/chat/completions', '/responses'] },
  { id: 'moonshotai/Kimi-K2.6', endpoints: ['/chat/completions', '/responses'] },
  { id: 'moonshotai/Kimi-K2.5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'z-ai/glm-5.3-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'z-ai/glm-5.3-flashx', endpoints: ['/chat/completions', '/responses'] },
  { id: 'zai-org/GLM-5.3', endpoints: ['/chat/completions', '/responses'] },
  { id: 'zai-org/GLM-5.2', endpoints: ['/chat/completions', '/responses'] },
  { id: 'zai-org/GLM-5.2-Fast', endpoints: ['/chat/completions', '/responses'] },
  { id: 'zai-org/GLM-5.1', endpoints: ['/chat/completions', '/responses'] },
  { id: 'zai-org/GLM-5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'MiniMaxAI/MiniMax-M3', endpoints: ['/chat/completions', '/responses'] },
  { id: 'MiniMaxAI/MiniMax-M2.7', endpoints: ['/chat/completions', '/responses'] },
  { id: 'MiniMaxAI/MiniMax-M2.5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xiaomi/mimo-v2.6-pro', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xiaomi/mimo-v2.6-pro-ultraspeed', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xiaomi/mimo-v2.6-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xiaomi/mimo-v2.5-pro', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xiaomi/mimo-v2.5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.8-Omni-Flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.8-Max-0902', endpoints: ['/chat/completions'] },
  { id: 'Qwen/Qwen3.8-Max', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.8-27B', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.8-Flash', endpoints: ['/chat/completions'] },
  { id: 'Qwen/Qwen3.7-Max', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.7-Plus', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.7-Flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.6-Max-Preview', endpoints: ['/chat/completions', '/responses'] },
  { id: 'Qwen/Qwen3.6-Plus', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meituan/LongCat-2.0', endpoints: ['/chat/completions'] },
  { id: 'stepfun/Step-5-Preview', endpoints: ['/chat/completions', '/responses'] },
  { id: 'stepfun/Step-3.7-Flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'stepfun/Step-3.5-Flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'tencent/hy3-paid', endpoints: ['/chat/completions', '/responses'] },
  { id: 'tencent/hy4-preview', endpoints: ['/chat/completions'] },
  { id: 'nvidia/nemotron-3-ultra-550b-a55b', endpoints: ['/chat/completions', '/responses'] },
  { id: 'thinkingmachines/inkling', endpoints: ['/chat/completions', '/responses'] },
  { id: 'thinkingmachines/inkling-small', endpoints: ['/chat/completions', '/responses'] },
  { id: 'poolside/laguna-s-2.1-free', endpoints: ['/chat/completions', '/responses'] },
  { id: 'inclusionai/ling-3.0-flash-sante:free', endpoints: ['/chat/completions'] },
  { id: 'stealth/space-bunny-alpha', endpoints: ['/chat/completions'] },
  { id: 'stealth/pixel-canary', endpoints: ['/chat/completions', '/responses'] },
  { id: 'claude-sonnet-5', endpoints: ['/messages'] },
  { id: 'claude-sonnet-4-6', endpoints: ['/messages'] },
  { id: 'claude-fable-5-1', endpoints: ['/messages'] },
  { id: 'claude-fable-5', endpoints: ['/messages'] },
  { id: 'claude-opus-5-5', endpoints: ['/messages'] },
  { id: 'claude-opus-5', endpoints: ['/messages'] },
  { id: 'claude-opus-4-8', endpoints: ['/messages'] },
  { id: 'claude-opus-4-7', endpoints: ['/messages'] },
  { id: 'claude-haiku-4-5-20251001', endpoints: ['/messages'] },
  { id: 'gpt-6-astra', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-6-sol', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-6-luna', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.6-sol', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.6-terra', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.6-luna', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.4', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.3-codex', endpoints: ['/chat/completions', '/responses'] },
  { id: 'gpt-5.4-mini', endpoints: ['/chat/completions', '/responses'] },
  { id: 'google/gemini-3.8-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'google/gemini-3.7-flash', endpoints: ['/chat/completions'] },
  { id: 'google/gemini-3.6-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'google/gemini-3.5-flash', endpoints: ['/chat/completions', '/responses'] },
  { id: 'google/gemini-3.5-flash-lite', endpoints: ['/chat/completions', '/responses'] },
  { id: 'google/gemini-3.1-flash-lite', endpoints: ['/chat/completions', '/responses'] },
  { id: 'sakana/fugu-ultra', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meta/muse-spark-1.1', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meta/muse-spark-1.2', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meta/muse-spark-1.2-contributor', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meta/muse-spark-1.3', endpoints: ['/chat/completions', '/responses'] },
  { id: 'meta/muse-spark-1.3-contributor', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xai/grok-4.5', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xai/grok-4.6', endpoints: ['/chat/completions', '/responses'] },
  { id: 'xai/grok-4.7', endpoints: ['/chat/completions', '/responses'] },
];

/** id → declared routes, for O(1) lookup on the request path. */
const BY_ID: ReadonlyMap<string, readonly ApiRoute[]> = new Map(
  ENDPOINTS.map((entry) => [entry.id, entry.endpoints]),
);

/** Ids the server did not declare routes for — logged once at activation. */
export function modelsWithoutDeclaredEndpoints(modelIds: readonly string[]): string[] {
  return modelIds.filter((id) => !BY_ID.has(id));
}

/**
 * The route to call for a model.
 *
 * Preference order is deliberate and matches the server's own advice:
 *  1. `/responses` when declared — it is the richer dialect and the one the
 *     tool-calling design targets.
 *  2. `/chat/completions` when that is all the model serves. Nine models are
 *     chat-completions-only, and sending one to `/responses` is a 400.
 *  3. `/messages` for a model that serves only that.
 *  4. A model the server said nothing about falls back to the documented
 *     default rather than a guess that will 400.
 */
export function routeFor(modelId: string): ApiRoute {
  const declared = BY_ID.get(modelId);
  if (declared !== undefined && declared.length > 0) {
    if (declared.includes('/responses')) {
      return '/responses';
    }
    if (declared.includes('/chat/completions')) {
      return '/chat/completions';
    }
    if (declared.includes('/messages')) {
      return '/messages';
    }
  }
  return '/responses';
}

/** The declared routes for a model, for diagnostics and tests. */
export function endpointsFor(modelId: string): readonly ApiRoute[] {
  return BY_ID.get(modelId) ?? [];
}
